In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3]) # a vector
b = np.array([4,5,6,7]) # a vector
c = np.array([[0,1,2,3],
             [4,5,6,7]])
d = np.zeros((2,4)) # 2x4 matrix of zeros
e = np.random.rand(2,5) # random 2x55 matrix of numbers between 0 and 1

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.5070954  0.93466465 0.58740897 0.73518464 0.46645532]
 [0.23090645 0.93299822 0.55156073 0.18312774 0.35303847]]


In [3]:
# element wise means handling data element by element

In [5]:
print(a * 0.1) 
print(c * 0.2) 
print(a * b) 
print(a * b * 0.2)
print(a * c)
print(a * e) # this gives an error becuz a n e dont have the number of columns

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [10]:
a = np.zeros((2,4))
b = np.zeros((4,10))
c = a.dot(b)
print(c.shape)

e = np.zeros((3,4))
f = np.zeros((4,6))
g = e.dot(f)
print(g.shape)

(2, 10)
(3, 6)


In [13]:
h = np.zeros((5,4)).T # T flips the rows and columns of a matrix
i = np.zeros((5,6)) 

j = h.dot(i)
print(j.shape)

(4, 6)


In [15]:
h = np.zeros((5,4))
i = np.zeros((5,6)) 

j = h.dot(i)
print(j.shape)

ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)