# single input

In [1]:
weights = [0.3, 0.2, 0.9]
wlrec = [0.65, 0.8, 0.8, 0.9]
inp = wlrec[0]

def ele_mul(number, vector):
    output=[0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def nn(inp, weights):
    return(ele_mul(inp,weights))

In [2]:
print(nn(inp,weights))

[0.195, 0.13, 0.5850000000000001]


# multi input/output

In [22]:
weights = [ [0.1, 0.1, -0.3],# hurt?
      [0.1, 0.2, 0.0], # win?
      [0.0, 1.3, 0.1] ]# sad?
toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0],wlrec[0],nfans[0]]

In [23]:
def w_sum(a,b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output


def vect_mat_mul(vect,matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect,matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input,weights)
    return pred

In [24]:
print(nn(input, weights))

[0.555, 0.9800000000000001, 0.9650000000000001]


## predicting on predictions

In [25]:
ih_wgt = [ #input hidden weights
    # toes  % win  fans
    [0.1,    0.2,   -0.1], # hid[0]
    [-0.1,   0.1,    0.9], # hid[1]
    [0.1,    0.4,    0.1] # hid[2]
]

hp_wgt = [
    # hid[0]  hid[1]  hid[2]
    [0.3,      1.1,    -0.3], # hurt?
    [0.1,      0.2,     0.0], # win?
    [0.0,      0.2,     0.0] # sad?
]

weights = [ih_wgt, hp_wgt]

In [31]:
def nn(input, weights):
    hid = vect_mat_mul(input, weights[0])
    print("Predicted HIDDEN layer:",hid)
    pred = vect_mat_mul(hid, weights[1])
    print("Predicted OUTPUT layer:",pred)

In [32]:
toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0],wlrec[0],nfans[0]]

nn(input, weights)


Predicted HIDDEN layer: [0.8600000000000001, 0.29499999999999993, 1.23]
Predicted OUTPUT layer: [0.21350000000000002, 0.14500000000000002, 0.05899999999999999]


# Numpy version

In [42]:
import numpy as np
# toes % win # fans
ih_wgt = np.array([ 
            [0.1, 0.2, -0.1], # hid[0]
            [-0.1,0.1, 0.9], # hid[1]
            [0.1, 0.4, 0.1]]).T # hid[2]
# hid[0] hid[1] hid[2]
hp_wgt = np.array([  
            [0.3, 1.1, -0.3], # hurt?
            [0.1, 0.2, 0.0], # win?
            [0.0, 1.3, 0.1] ]).T # sad?
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred
toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0],wlrec[0],nfans[0]])
pred = neural_network(input,weights)
print(pred)

[0.2135 0.145  0.5065]


In [38]:
x = np.array([
    [1.,2.,3.],
    [4.,5.,6.],
    [7.,8.,9.]
])
print(x.T)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
